#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the SilverStripe image!
SilverStripe is installed in /var/www.
Log into SilverStripe at http://${PUBLIC_IP}/.
MySQL is configured for user root with password {mysql_root_password}.
Your website configuration lies at:
- /etc/nginx/sites-available/000-default.conf
Enjoy!
EOF

